

spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://122.51.31.23/skt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC 
    username: root 
    password: 123456

    
  mvc:
    view:
      prefix: /templates/
      suffix: .html
      
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    encoding: UTF-8
    servlet: 
     content-type: text/html
    mode: HTML5
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
    

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
logging:
  level:
    com.app.OOS: debug
  config: classpath:log4j2.yml
